export interface IHash {
  [details: string]: string;
}

export const colorMap: IHash = {
  'normal': '#C9B5B5',
  'fighting': '#D4A56E',
  'flying': '#ACC4E4',
  'poison': '#69538D',
  'ground': '#CC9F6D',
  'rock': '#585857',
  'bug': '#A3C98A',
  'ghost': '#595766',
  'steel': '#AAAAAA',
  'fire': '#EB663E',
  'water': '#5EA1E0',
  'grass': '#6DBD5B',
  'electric': '#F8C53A',
  'psychic': '#F1A3CA',
  'ice': '#8BDEF3',
  'dragon': '#A02929',
  'dark': '#333333',
  'fairy': '#FA92B5',
  'unknown': 'white',
  'shadow': 'grey',
};

export const backgroundColorMap: IHash = {
  'normal': '#F0F0F0',
  'fighting': '#F3EAE0',
  'flying': '#E0E6EE',
  'poison': '#746886',
  'ground': '#F0E6DB',
  'rock': '#7A7976',
  'bug': '#CEEBBC',
  'ghost': '#3D3D41',
  'steel': '#7E7E7E',
  'fire': '#F8E8E3',
  'water': '#E9F0FA',
  'grass': '#E3F1E0',
  'electric': '#FDFBE8',
  'psychic': '#F8ECF2',
  'ice': '#EFF8FA',
  'dragon': '#524F4F',
  'dark': '#1A1A1A',
  'fairy': '#FDF2F6',
  'unknown': 'white',
  'shadow': 'grey',
};

export const baseTheme: IHash = {
  'normal': 'light',
  'fighting': 'light',
  'flying': 'light',
  'poison': 'dark',
  'ground': 'light',
  'rock': 'dark',
  'bug': 'light',
  'ghost': 'dark',
  'steel': 'dark',
  'fire': 'light',
  'water': 'light',
  'grass': 'light',
  'electric': 'light',
  'psychic': 'light',
  'ice': 'light',
  'dragon': 'dark',
  'dark': 'dark',
  'fairy': 'light',
  'unknown': 'light',
  'shadow': 'dark',
};
